# Generated by Django 4.2.3 on 2023-07-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_docsobjects_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsobjects',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
